# Generated by Django 3.2.6 on 2021-09-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210921_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_up',
            name='Descarga_archivo',
            field=models.FileField(upload_to='media/archivos/'),
        ),
    ]
