# Generated by Django 3.2.6 on 2021-09-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_files_up_descarga_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_up',
            name='Descarga_archivo',
            field=models.FileField(upload_to='media/archivos/'),
        ),
    ]
